### ISSUE TITLE
We need caching !

### ISSUE THREAD

**Issue by uczpre** [onebeastchris/customplayerheads#30]
We dont always have the internet (or authentication lol) required to access the server for skin info !
imagine playing on Lan or with online-mode set to false to play with a friend who doesnt have minecraft or internet :(
so sad , pls fix

**Comment by onebeastchris** [comment]
The texture added to the heads is just copied from the player, and doesn't require any online access. As for getting skulls with a command, catching that is impossible since there are thousands of skins..
