### ISSUE TITLE
heads of players without a license

### ISSUE THREAD

**Issue by MrDV13** [onebeastchris/customplayerheads#36]
Hello, I'm using Google Translate, so there may be some errors.

My main question is how this can be used with accounts that do not have a minecraft license. How can I make sure that their skin is put on the players’ heads? As I understand it, the mod requests skins from mojang, is it possible to make a request from another site (such as Ely By) or add the skin to the server memory through a command, and then use the skin for the head?

**Comment by onebeastchris** [comment]
When dropping heads upon dying, this mod just takes the skin values that are currently applied to the player. Only the `/getskull` command uses the Geyser API for Bedrock players, or Mojang API for Java players. I do not plan to add other api's at the moment.
