### ISSUE TITLE
heads lose their lore when placed and then picked up

### ISSUE THREAD

**Issue by Barkells** [onebeastchris/customplayerheads#38]
Im not sure if this is even fixable but trying my luck anyway lol

**Comment by onebeastchris** [comment]
To quote the readme file:

> Because of https://bugs.mojang.com/browse/MC-174496, it is recommended to use a mod like https://modrinth.com/mod/headfix to keep Custom Head Names when breaking the head.

That should also resolve lore not being stored.

**Comment by Barkells** [comment]
It did not work lol alas

**Comment by onebeastchris** [comment]
Just tested on my end - that's unfortunately a thing vanilla does. Placing and destroying player heads makes them lose their lore :/
Unfortunately, there's nothing I can do about that
